CANDLE_BASE_GAP=1.15
CANDLE_RED='red'
CANDLE_BLUE='blue'
CANDLE_CROSS='cross'
CANDLE_GAP_LONG='long'
CANDLE_GAP_SHORT='short'
STATUS_NEUTRAL='N'
STATUS_BUYING='B'
STATUS_SELLING='S'

INIT_MY_PAPER_MONEY=1000000
INIT_STATUS_CURRENT_STATUS=STATUS_NEUTRAL
INIT_STATUS_CURRENT_MAX=0.0

BITCOIN_BUY_RATE=0.002